DELIMITER //
CREATE TRIGGER співробтники_чек
BEFORE INSERT ON співробітники
FOR EACH ROW
  BEGIN
    IF (NEW.ТрудовийСтаж) > 2017  THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'WRONG VALUE';
    END IF;
  END //
DELIMITER ;